module nand_tb;
reg a,b;
wire y;

nand_data uut(.a(a),
	.b(b),
	.y(y));
initial
begin
$dumpfile("nand.vcd");
$dumpvars(0,nand_tb);
$monitor("t=%0t a=%b b=%b y=%b",$time,a,b,y);
a=0;b=0;
#10
a=0;b=1;
#10
a=1;b=0;
#10
a=1;b=1;
#10
$finish;
end
endmodule
