module half_adder_tb;
reg a,b;
wire s,c;

half_adder_st uut(.a(a),.b(b),.s(s),.c(c));

initial
begin
$dumpfile("half_adder.vcd"); 
$dumpvars(0,half_adder_tb);
$monitor("t=%0t,a=%b,b=%b,s=%b,c=%b",$time,a,b,s,c);

a=0;b=0; #10
b=1;#10
a=1;b=0;#10
b=1;#10
$finish;
end
endmodule
